// config/index.tsx
import { cookieStorage, createStorage } from "wagmi"; // Use 'wagmi' directly (Wagmi v2+)
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import {
  mainnet,
  arbitrum,
  base,
  scroll,
  polygon,
  hedera,
} from "@reown/appkit/networks";
import type { Chain } from "viem"; // Import Chain type for explicit typing

// Define custom networks
export const omegaChain: Chain = {
  id: 1313161768,
  name: "Omega Network",
  network: "omega",
  nativeCurrency: {
    decimals: 18,
    name: "Omega",
    symbol: "OMEGA",
  },
  rpcUrls: {
    default: {
      http: ["https://0x4e454228.rpc.aurora-cloud.dev"],
    },
    public: {
      http: ["https://0x4e454228.rpc.aurora-cloud.dev"],
    },
  },
  blockExplorers: {
    default: {
      name: "Omega Explorer",
      url: "https://0x4e454228.explorer.aurora-cloud.dev",
    },
  },
  testnet: false,
};

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID;

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error(
    "NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local"
  );
}

// Define supported networks, explicitly typed as a non-empty array of Chains
export const networks: [Chain, ...Chain[]] = [
  mainnet,
  arbitrum,
  base,
  scroll,
  polygon,
  hedera,
  omegaChain,
]; // Add other desired networks

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }), // Use cookieStorage for SSR
  ssr: true, // Enable SSR support
  projectId,
  networks, // Pass the explicitly typed networks array
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
